### ISSUE TITLE
Light Code Feedback

### ISSUE THREAD

**Issue by dginovker** [Ravo92/Patch-2.22-Launcher#14]
Feel free to close this issue after you read it, just here providing some feedback:

* Arguments that are full words should have two dashes (`--like --this`), one dash is reserved for short form variations (`-l -t`) https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/GameSelection/Program.cs#L18
* The default (no arguments passed in) should be the most reasonable approach a user wants. I think you're intentionally exiting if they open the wrong .exe but without user feedback it can be confusing https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/GameSelection/Program.cs#L20
* I like what you've done here where the first code branch is the shortest, it's good style: https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/BFME1/Program.cs#L20
* Don't leave comments that don't make sense going forwards, and don't leave commented out code (unless there's an explicit comment explaining when you want to put that code back in): https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/BFME1/Program.cs#L16
* Always try-catch and print out the errors in your Tasks, otherwise you won't see their stacktraces and will go mad debugging: https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/Helper/ZIPFileHelper.cs#L14 (this could be the culprit for weird issues like #9 )
* Amazing work here https://github.com/Ravo92/Patch-2.22-Launcher/blob/main/Helper/RegistryService.cs
* Great that it's open source, making debugging a lot easier :)

**Comment by Ravo92** [comment]
Thank you for this heavy valuable feedback! I will keep this issue open as long ther are basic failures and mistakes in pattern.

**Comment by Ravo92** [comment]
1 + 2
I changed the exe startup behaviour to: "Always start updater.exe when clicked on wrong exe". I also changed to double dash:
676f65024961e1c9c2cff7ec1a9a067ccf6f8106

3
Thank you :D

4
I removed the comments, I'll switch for the new and next windows to .net maui were the dpi scaling problem shouldn't be that big of an issue. 7930275064b09cfee788ae7a7afee6e139b53066

5
I added a try-catch block there with a null-return if error and logging the caught error. I know what returning null is the worst you can do, but i have no idea for now, how to make this method more clean. 678b51b17f8d66e17940e9b7272ed966978f6985

6
Thank you - I still made it better, since there is a "IsNotNull" Boolean, which I only used once and then proceeded with "!= null" so wasn't perfect yet. 0bb358dd22185560af38ba96c5228fd5c96c2ec4

**Comment by dginovker** [comment]
Looks great! `Error.log` will work great for people immediately closing and not reading the error message too.

Keep up the good work!
